# Generated by Django 5.0.6 on 2024-05-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_books_owner_books_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
