# Generated by Django 5.0.6 on 2024-05-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_books_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.PositiveIntegerField(default=0, null=True)),
                ('two', models.PositiveIntegerField(default=0, null=True)),
                ('three', models.PositiveIntegerField(default=0, null=True)),
                ('four', models.PositiveIntegerField(default=0, null=True)),
                ('five', models.PositiveIntegerField(default=0, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='books.books')),
            ],
        ),
    ]
