# Generated by Django 5.0.6 on 2024-05-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default='No description', max_length=255),
            preserve_default=False,
        ),
    ]
