# Generated by Django 5.0.6 on 2024-05-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
