# Generated by Django 5.0.6 on 2024-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
