# Generated by Django 5.0.6 on 2024-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.TextField(),
        ),
    ]
