# Generated by Django 5.0.6 on 2024-05-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_weeklyrecomendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyRecomendation',
            new_name='WeeklyRecommendation',
        ),
    ]
